# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyCalloutView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyCalloutView

  target 'MyCalloutViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyCalloutViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end



    pod 'AMap3DMap'

end
